In [1]:
import numpy as np

a = np.array([[1,2,3,4,5,6],[8,9,10,11,12,14]])
print(a)

[[ 1  2  3  4  5  6]
 [ 8  9 10 11 12 14]]


In [2]:
b = np.array([6.0,1,5])
print(b)

[6. 1. 5.]


In [5]:
#get type
b.dtype

dtype('float64')

In [3]:
#getsize
b.itemsize

8

In [7]:
#get total size
b.size * b.itemsize

24

In [8]:
#get total size another way
b.nbytes


24

In [11]:
a1 = np.array([[5,9,8,5,8],[8,7,5,6,2]])
print(a1)


[[5 9 8 5 8]
 [8 7 5 6 2]]


In [12]:
#get the shape of the array
a1.shape


(2, 5)

In [15]:
#get the specific elements[row,column]
a1[1,-5]

8

In [16]:
#get specific row
a1[0,:]

array([5, 9, 8, 5, 8])

In [17]:
#get the column
a1[:, 1]

array([9, 7])

In [18]:
#getting much into it [startindex:endindex:stepsize]

a1[0,1:3]

# it would be 0 array, 1 index to find the end index, 3 the stepsize to skip


array([9, 8])

In [23]:
#update the array
a1[1,4]=15
print(a1)


[[ 5  9  8  5  8]
 [ 8  7  5  6 15]]


In [24]:
#to update the column

a1[:,2]=7
print(a1)

[[ 5  9  7  5  8]
 [ 8  7  7  6 15]]


In [26]:
# 3d array example

b1 = np.array([[[1,3],[4,5]],[[6,7],[8,9]]])
print(b1)


[[[1 3]
  [4 5]]

 [[6 7]
  [8 9]]]


In [27]:
#get the specific element from the upper 3d array example
b1[0,1,1]


5

In [28]:
#get the specific element from the upper 3d array example
b1[0,1,:]


array([4, 5])

In [29]:
#get the specific element from the upper 3d array example
b1[:,1,:]


array([[4, 5],
       [8, 9]])

In [31]:
#replace
b1[:,1,:] = [[5,5],[5,5]]
print(b1)

[[[1 3]
  [5 5]]

 [[6 7]
  [5 5]]]


In [33]:
#initializing different Types of arrays

#All zero matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
#all 1s matrix and set datatype 

np.ones((3,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [6]:
#any other number

np.full((2,2),77)

array([[77, 77],
       [77, 77]])

In [10]:
#any other number(full like)
import numpy as np
a1 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a1)


np.full(a1.shape, 3)


[[1 2 3 4 5]
 [6 7 8 9 0]]


array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [11]:
# randomm decimal numbers
np.random.rand(3,2)


array([[0.23031804, 0.37106887],
       [0.1212593 , 0.92833177],
       [0.50427276, 0.86234727]])

In [41]:
#random integer numbers here 5 will limit the execution we can't exceed above 5. try to execute this 
# multiple time
np.random.randint(5, size=(2,2))


array([[4, 3],
       [0, 1]])

In [43]:
#the identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [50]:
#it will repeat the array by the repeat times
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
#exercise
out = np.ones((5,5))
print(out)

x = np.zeros((3,3))
x[1,1] = 9
print(x)

out[1:4,1:4] = x
print(out)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [87]:
# BE CAREFUL WHEN COPYING ARRAYS

a = np.array([5,6,7])
b=a.copy()#make sure to use copy so that we can see the actual value
b[1]=10
print(b)
print(a)



[ 5 10  7]
[5 6 7]


In [88]:
# Mathematics

a = np.array([1,2,3])
print(a)


[1 2 3]


In [89]:
a + 2

array([3, 4, 5])

In [90]:
a - 2


array([-1,  0,  1])

In [91]:
a * 2

array([2, 4, 6])

In [94]:
#add two arrays
b = np.array([4,5,6])
a + b


array([5, 7, 9])

In [100]:
###Linear Algebra
a  = np.ones((2,3))
print(a)

# it will create array with 2's
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [101]:
# multiply to matrix array it uses this matmul
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [105]:
#find the determinant linalg - Linear algebra
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics 

In [106]:
stats = np.array([[2,5,8],[1,4,7]])
stats

array([[2, 5, 8],
       [1, 4, 7]])

#this will min array with axis 0
np.min(stats, axis=0)


In [112]:
np.max(stats)

8

# Reorganizing Arrays

In [149]:
bef = np.array([[2,5,9,0],[5,6,8,5]])
print(bef)



[[2 5 9 0]
 [5 6 8 5]]


In [151]:
after = bef.reshape((4,2))
print(after)

[[2 5]
 [9 0]
 [5 6]
 [8 5]]


In [157]:
#Vertical stacking 

v1 = np.array([1,2,3,4,5])
v2 = np.array([7,8,9,0,5])

np.vstack([v1,v2,v1,v2])
        

array([[1, 2, 3, 4, 5],
       [7, 8, 9, 0, 5],
       [1, 2, 3, 4, 5],
       [7, 8, 9, 0, 5]])

In [165]:
#horizontal Stacking (( [[ barckets works too
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h2,h1))


array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])